# 导航菜单
menu:
  归档: /archives/ || fa-solid fa-boxes-packing
  分类: /categories/ || fa-solid fa-sitemap
  图库: /img_page/ || fa-solid fa-images
  标签: /tags/ || fa-solid fa-tags
  收藏||fa-solid fa-star:
    Music: /music/ || fas fa-music
    Movie: /movies/ || fa-solid fa-video
  链接: /link/ || fa-solid fa-paperclip
  留言板: /guestbook/ || fa-solid fa-comment-dots

# A simple 404 page
error_404:
  enable: true
  subtitle: '页面没有找到'
  background: //file.mo7.cc/api/public/bz

# 代码渲染
highlight_theme: mac # default / darker / pale night / light / ocean
highlight_copy: true #代碼複製按鈕
highlight_shrink: none # 代码框展开按钮
highlight_height_limit: 130 # unit: px

# 社交图标
social:
  fab fa-github: //github.com/mo7cc || Github
  fas fa-envelope: mailto:mo7@mo7.cc || Email
  fa fa-rss: /atom.xml || RSS

# 主頁文章節選
index_post_content:
  method: 3
  length: 300 # if you set method to 2 or 3, the length need to config

# 頂部圖
default_top_img: '//file.mo7.cc/api/public/bz'
index_img: '//file.mo7.cc/api/public/bz?idx=1'
archive_img: '//file.mo7.cc/api/public/bz?idx=2'
tag_img: '//file.mo7.cc/api/public/bz?idx=3'
tag_per_img: '//file.mo7.cc/api/public/bz?idx=4'
category_img: '//file.mo7.cc/api/public/bz?idx=5'
category_per_img: '//file.mo7.cc/api/public/bz?idx=6'

# 文章封面
cover:
  # 是否顯示文章封面
  index_enable: true
  aside_enable: true
  archives_enable: true
  # 封面顯示的位置
  # 三個值可配置 left , right , both
  position: both
  # 當沒有設置cover時，默認的封面顯示
  default_cover:
    - //file.mo7.cc/api/public/bz?idx=0
    - //file.mo7.cc/api/public/bz?idx=1
    - //file.mo7.cc/api/public/bz?idx=2
    - //file.mo7.cc/api/public/bz?idx=3
    - //file.mo7.cc/api/public/bz?idx=4
    - //file.mo7.cc/api/public/bz?idx=5
    - //file.mo7.cc/api/public/bz?idx=6
    - //file.mo7.cc/api/public/bz?idx=7
    - //file.mo7.cc/api/public/bz?idx=8

# 文章頁相關配置
post_meta:
  page:
    date_type: both # created or updated or both 主頁文章日期是創建日或者更新日或都顯示
    date_format: relative # date/relative 顯示日期還是相對日期
    categories: true # true or false 主頁是否顯示分類
    tags: true # true or false 主頁是否顯示標籤
    label: true # true or false 顯示描述性文字
  post:
    date_type: both # created or updated or both 文章頁日期是創建日或者更新日或都顯示
    date_format: relative # date/relative 顯示日期還是相對日期
    categories: true # true or false 文章頁是否顯示分類
    tags: true # true or false 文章頁是否顯示標籤
    label: true # true or false 顯示描述性文字

# 文章版權
post_copyright:
  enable: true
  decode: true
  license: CC BY-NC-SA
  license_url: https://creativecommons.org/licenses/by-nc-sa

# 文章打賞
reward:
  enable: true
  QR_code:
    - img: //file.mo7.cc/static/img/wx_proceeds.jpg
      link: //file.mo7.cc/static/img/wx_proceeds.jpg
      text: 微信

# TOC
toc:
  post: true
  page: false
  number: true
  expand: false
  style_simple: true # for post

# 相關文章
related_post:
  enable: true
  limit: 6 # 顯示推薦文章數目
  date_type: created # or created or updated 文章日期顯示創建日或者更新日

## 文章分頁按鈕
post_pagination: false

## 頭像
avatar:
  img: //file.mo7.cc/static/lxh_gif/lxh_71.gif
  effect: false # 頭像會一直轉圈

## 图片描述文字
photofigcaption: true

## 複製相關配置
copy:
  enable: true
  copyright:
    enable: true
    limit_count: 300

## Footer 設置
footer:
  owner:
    enable: false
    since: 2022
  custom_text: <div class="icpwrapper">
    <a class="icp" href="//mo7.cc" target="_blank"> © 2022 墨七 </a>
    <a class="icp" href="https://beian.miit.gov.cn" target="_blank">
    <img src="//file.mo7.cc/static/img/beian.png" />
    陕ICP备2022011574号
    </a>
    <a
    class="icp"
    target="_blank"
    href="https://www.beian.gov.cn/portal/registerSystemInfo?recordcode=11010802020088"
    >
    <img src="//file.mo7.cc/static/img/gongan.png" />
    京公网安备11010802020088号
    </a>
    </div>

######################   右下角按鈕  ######################
# 簡繁轉換
translate:
  enable: false
  # 默認按鈕顯示文字
  default: 繁
  #網站默認語言，1: 繁體中文, 2: 簡體中文
  defaultEncoding: 2
  #延遲時間,若不在前, 要設定延遲翻譯時間, 如100表示100ms,默認為0
  translateDelay: 0
  #博客網址
  cookieDomain: 'https://blog2.mo7.cc'
  #當文字是簡體時，按鈕顯示的文字
  msgToTraditionalChinese: '繁'
  #當文字是繁體時，按鈕顯示的文字
  msgToSimplifiedChinese: '簡'

# 夜間模式
darkmode:
  enable: true
  # dark mode和 light mode切換按鈕
  button: true
  # 自動切換 dark mode和 light mode
  # autoChangeMode: 1  跟隨系統而變化，不支持的瀏覽器/系統將按照時間晚上6點到早上6點之間切換為 dark mode
  # autoChangeMode: 2  只按照時間晚上6點到早上6點之間切換為 dark mode
  # autoChangeMode: false 取消自動切換
  autoChangeMode: 2

# 閲讀模式
readmode: true

######################   側邊欄設置  ######################
# 側邊排版
aside:
  enable: true
  hide: false
  button: true
  mobile: true # 手機頁面（ 顯示寬度 < 768px ）是否顯示aside內容
  position: left # left or right
  card_author:
    enable: true
    description: ''
    button:
      enable: true
      icon: fab fa-github
      text: Github
      link: //github.com/mo7cc
  card_announcement: #公告
    enable: true
    content: 暂无公告
  card_recent_post: # 最近更新
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
  card_categories: # 分类
    enable: true
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
  card_tags: # 标签
    enable: true
    limit: 40 # if set 0 will show all
    color: true
  card_archives: # 归档
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true

# 訪問人數 busuanzi (UV 和 PV)
busuanzi:
  site_uv: false
  site_pv: false
  page_pv: false
# 運行時間
runtimeshow:
  enable: true
  publish_date: 2021/9/5 19:20:00 #相识纪念日
  ##網頁開通時間
  #格式: 月/日/年 時間
  #也可以寫成 年/月/日 時間

# 最新評論
# Aside widget - Newest Comments
newest_comments:
  enable: true
  sort_order: # Don't modify the setting unless you know how it works
  limit: 6
  storage: 10 # unit: mins, save data to localStorage
  avatar: true

# 評論
comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Waline/Utterances/Facebook Comments/Twikoo
  use:
    - Twikoo
  text: false # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: false
  count: true # Display comment count in top_img
  card_post_count: false # Display comment count in Home Page
# waline - A simple comment system with backend support fork from Valine
# //waline.js.org/
twikoo:
  envId: 'https://tkserver.mo7.cc'
  region:
  visitor: true
  option:
## 管理密码  asdasd55555
## 昵称输入 meichangliang    显示管理按钮

sharejs:
  enable: true
  sites: wechat,weibo,qq,facebook,twitter #想要顯示的內容

# npm install hexo-generator-search --save
local_search:
  enable: true

# 廣告
google_adsense:
  enable: false
  auto_ads: false
  js: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
  client: # 填入個人識別碼
  enable_page_level_ads: true

######################   美化/特效  ######################
# 自定義主題色
theme_color:
  enable: true
  main: '#5D6D7E' #齿轮和滚动条
  paginator: '#2874A6' #序号框颜色
  button_hover: '#AF7AC5' # 按钮 hover 颜色
  text_selection: '#5499C7' # 文章文字选中颜色
  link_color: '#7D3C98' #文章中链接的颜色
  meta_color: '#858585' #文章列表的时间日期文字颜色
  hr_color: '#99A3A4' # 文章中摩托车颜色
  code_foreground: '#F47466' # 文章中的高亮文本
  code_background: 'rgba(27, 31, 35, 0.1)' #文章中高亮文字的背景色
  toc_color: '#AF7AC5' #侧边栏进度器标题选中颜色
  blockquote_padding_color: '#49b1f5' #多行引用边线颜色
  blockquote_background_color: '#49b1f5' #多行引用内容颜色
  scrollbar_color: '#5D6D7E'

# 網站背景
background: '#a18cd1'

# footer 背景
footer_bg: true

# 點擊出現愛心
click_heart:
  enable: true
  mobile: false
# 彩带
canvas_ribbon:
  enable: true
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: true #設置是否每次點擊都更換綵帶
  mobile: false # false 手機端不顯示 true 手機端顯示
# 美化頁面顯示
beautify:
  enable: true
  field: post # site/post
  title-prefix-icon: '\f586'
  title-prefix-icon-color: '#AF7AC5'

# 主頁subtitle
subtitle:
  enable: true
  # 打字效果
  effect: true
  # 循環或者只打字一次
  loop: true
  # source 調用第三方服務
  # source: false 關閉調用
  # source: 1  調用一言網的一句話（簡體） https://hitokoto.cn/
  # source: 2  調用一句網（簡體） http://yijuzhan.com/
  # source: 3  調用今日詩詞（簡體） https://www.jinrishici.com/
  # subtitle 會先顯示 source , 再顯示 sub 的內容
  source: 3
  # (如果有英文逗號' , '，請使用轉義字符 &#44;)
  # 如果關閉打字效果，subtitle只會顯示sub的第一行文字
  sub:
    - 简单快乐，理应如此
# 加載動畫 Loading Animation
preloader: false

# PWA
pwa:
  enable: true
  manifest: /img/pwa/manifest.json
  apple_touch_icon: /img/pwa/512.png
  favicon_32_32: /img/pwa/32.png
  favicon_16_16: /img/pwa/16.png
  mask_icon: /img/pwa/512.png

# 字數統計
wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

# Snackbar 彈窗
snackbar:
  enable: false
  position: top-right
  bg_light: '#7D3C98' #light mode時彈窗背景
  bg_dark: '#5499C7' #dark mode時彈窗背景

# Open Graph
Open_Graph_meta: true

# Instantpage 预加载
instantpage: true

# Pangu
pangu:
  enable: true
  field: post # site/post

#### 分析統計  ####
# baidu_analytics: '81de35477a983300ce59c5cb886ce2c5'
# google_analytics: 'G-CNCBTNTTKV'
# microsoft_clarity: 'c8jcnhzwfa'
###  额外的标签
inject:
  head:
    # rss 订阅
    - <link rel="alternate" type="application/rss+xml" title="墨七" href="/atom.xml" />
    - <link rel="alternate" type="application/atom+xml" title="墨七" href="/atom.xml" />
    # css
    - <link rel="stylesheet" href="/assets/css/public.css">
  bottom:
    - <script src="/assets/js/public.js"></script>

### CDN
CDN:
  # The CDN provider of internal scripts (主題內部 js 的 cdn 配置)
  # option: local/jsdelivr
  # Dev version cannot choose jsdelivr (dev版的主題不能設置為 jsdelivr)
  internal_provider: local
  # The CDN provider of third party scripts (第三方 js 的 cdn 配置)
  # option: local/jsdelivr
  # when set it to local, you need to install hexo-butterfly-extjs
  third_party_provider: local
  option:
    # main_css:
    # main:
    # utils:
    # translate:
    # local_search:
    # algolia_js:
    # algolia_search_v4:
    # instantsearch_v4:
    # pjax:
    # gitalk:
    # gitalk_css:
    # blueimp_md5:
    # valine:
    # disqusjs:
    # disqusjs_css:
    # twikoo:
    # waline_js:
    # waline_css:
    # sharejs:
    # sharejs_css:
    # mathjax:
    # katex:
    # katex_copytex:
    # katex_copytex_css:
    # mermaid:
    # canvas_ribbon:
    # canvas_fluttering_ribbon:
    # canvas_nest:
    # lazyload:
    # instantpage:
    # typed:
    # pangu:
    # fancybox_css_v4:
    # fancybox_v4:
    # medium_zoom:
    # snackbar_css:
    # snackbar:
    # activate_power_mode:
    # fireworks:
    # click_heart:
    # ClickShowText:
    # fontawesomeV6:
    # flickr_justified_gallery_js:
    # flickr_justified_gallery_css:
    # aplayer_css:
    # aplayer_js:
    # meting_js:
    # prismjs_js:
    # prismjs_lineNumber_js:
    # prismjs_autoloader:
